import { Subject, Chapter, Topic, Question, Lesson } from '../types';
import { INDIAN_LANGUAGES } from '../data/indianLanguages';
import { localizeQuestionFn } from './questionTranslations';
import { localizeChapterFn, localizeTopicFn } from './chapterTranslations';

// Comprehensive UI Translations for all main sections of the website
export const COMPREHENSIVE_UI_TRANSLATIONS: Record<string, Record<string, string>> = {
  en: {
    tagline: 'Learn Smarter • Practice Better',
    study_mode: 'Study Mode',
    classes: 'Classes',
    reading_coach: 'Reading Coach',
    vocabulary: 'Vocabulary',
    ask_doubt: 'Ask Doubt',
    revision: 'Revision',
    exam_prep: 'Exam Prep',
    ask_ai_tutor: 'Ask AI Tutor',
    ask_ai: 'Ask AI',
    study_now: 'Study [Learn]',
    practice: 'Practice',
    mastery: 'Mastery',
    min: 'mins',
    mins: 'mins',
    overall_mastery: 'Subject Mastery Level',
    in_curriculum: 'in this curriculum',
    curriculum_chapters: 'Curriculum Chapters',
    chapters: 'Chapters',
    dashboard: 'Dashboard',
    catalog: 'Catalog',
    mock_tests: 'Mock Test',
    login_onboard: '+ Login / Onboard',
    switch_language: 'Select Indian Language',
    languages_label: 'Languages',
    popular_languages: 'Popular Languages',
    all_languages: 'All Indian Languages (22 Official)',

    // Landing Page Hero
    hero_badge: 'DESHNA AI LEARNING HUB • FOR GRADES 1 TO 11',
    hero_languages_badge: '22+ Indian Languages • বাংলা, हिन्दी, मराठी, etc.',
    hero_headline_1: 'One AI Learning Platform.',
    hero_headline_2: 'Every Grade. Every Subject.',
    hero_headline_3: 'Personalized for Every Student.',
    hero_description: '"Learn Smarter. Practice Better. Grow Every Day." From Grade 1 foundational phonics to Grade 11 specialized streams across CBSE, ICSE, and State Boards—with adaptive practice, interactive reading coach, and 24/7 AI tutor.',
    
    // Auth & Navigation
    portal_system_admin: 'System Admin',
    portal_student_login: 'Student Roll Login',
    portal_parent_login: 'Parent Mobile Access',
    enter_admin_email: 'Administrator Email',
    enter_admin_password: 'Password',
    enter_student_roll: 'Enter Student Roll Code (e.g. DESH-GR3-8821)',
    enter_student_name: 'Student Full Name',
    select_class_grade: 'Select Class / Grade',
    select_board: 'Select Education Board',
    parent_whatsapp_phone: 'Parent WhatsApp Phone',
    login_as_student: 'Login as Student',
    register_new_student: 'Register & Start Learning',
    login_as_parent: 'Verify Parent Phone & Access',
    login_as_admin: 'Login to Admin Console',
    quick_demo_access: '✨ Quick Demo Fast-Access:',
    quick_demo_grade3: '👦 Grade 3 CBSE (Alex)',
    quick_demo_grade10: '👧 Grade 10 Board (Sara)',
    quick_demo_grade11: '🔬 Grade 11 Science (Rahul)',
    explore_all_classes: '📚 Explore All Classes (Grade 1 - 11)',
    start_learning_free: 'Start Free AI Practice Now',

    // Landing Page Sections
    curriculum_title: 'Complete Grade 1 to 11 Curriculum Directory',
    curriculum_subtitle: 'Explore subjects, chapters, interactive quizzes, and AI tutor explanations across all 11 grades.',
    features_title: 'Powerful AI Tools for Smarter Learning',
    features_subtitle: 'Everything a school student needs to excel, stay motivated, and build deep conceptual clarity.',
    feature_reading_coach_title: 'Interactive AI Reading Coach',
    feature_reading_coach_desc: 'Real-time phonics guidance, speech assessment, word-by-word pronunciation support, and story comprehension.',
    feature_doubt_title: 'Instant 24/7 Step-by-Step Doubt Solver',
    feature_doubt_desc: 'Snap a photo or type any homework question. Get friendly, step-by-step Socratic guidance that builds true understanding.',
    feature_revision_title: 'Smart Spaced Repetition Mastery Vault',
    feature_revision_desc: 'Never forget what you learn. Leitner-box spaced repetition ensures topics move from short-term to permanent memory.',
    feature_exam_title: 'Board & Competitive Exam Prep',
    feature_exam_desc: 'Adaptive mock tests, timed question series, previous year papers, and performance analytics for CBSE, ICSE & State Boards.',

    // Student Dashboard
    hello_greeting: 'Hello',
    day_streak: 'Day Streak',
    streak_subtext: 'Daily Study Habit',
    mastery_points: 'Mastery Points',
    points_subtext: 'Earned through practice',
    reading_speed: 'Reading Speed',
    speed_subtext: 'Words per minute',
    words_mastered: 'Words Mastered',
    vocab_subtext: 'In Vocabulary Vault',
    daily_study_plan: 'Your Daily Study Plan',
    daily_plan_desc: 'AI-tailored 30-minute practice session based on your mastery and upcoming topics.',
    time_target: 'Daily Target',
    regenerate_plan: 'Adjust Plan',
    start_activity: 'Start Activity',
    completed: 'Completed',
    continue_learning: 'Continue Learning',
    all_subjects: 'All Subjects',
    chapters_count: 'Chapters',
    questions_count: 'Questions',
    mastery_level: 'Mastery',
    start_subject: 'Open Subject',
    quick_practice: 'Quick Practice Questions',
    due_revisions: 'Items Due for Revision',
    revise_now: 'Revise Now',
    recent_badges: 'Your Achievements & Badges',

    // Subject & Chapter View
    chapter_roadmap: 'Chapter Roadmap & Practice',
    learning_objectives: 'Learning Objectives',
    est_time: 'Est. Time',
    minutes: 'mins',
    start_chapter: 'Start Chapter',
    concept_notes: 'Concept Notes & Explanations',
    practice_tab: 'Practice & Quizzes',
    summary_tab: 'Quick Summary & Key Formulas',
    key_takeaways: 'Key Takeaways & Formulas',
    topics_in_chapter: 'Topics in this Chapter',
    difficulty: 'Difficulty',
    easy: 'Easy',
    medium: 'Medium',
    hard: 'Hard',
    advanced: 'Advanced',

    // Practice Questions
    question_label: 'Question',
    of_label: 'of',
    check_answer: 'Check Answer',
    next_question: 'Next Question',
    previous_question: 'Previous Question',
    show_hint: 'Need a Hint?',
    hide_hint: 'Hide Hint',
    explanation_title: 'Step-by-Step Explanation',
    correct_feedback: 'Correct! Brilliant work! 🌟',
    incorrect_feedback: 'Not quite. Let us review the correct concept:',
    practice_completed_title: 'Practice Session Completed! 🎉',
    your_score: 'Your Score',
    points_earned: 'Points Earned',
    retake_quiz: 'Practice Again',
    next_chapter: 'Proceed to Next Topic',
    ask_ai_explain: 'Ask AI Tutor to Explain this in Detail',

    // General
    search_placeholder: 'Search subjects, chapters, questions...',
    all_grades: 'All Grades',
    grade: 'Grade',
    board: 'Board',
    stream: 'Stream',
    back_to_dashboard: '← Back to Dashboard',
    back_to_subjects: '← Back to Subjects',
  },

  bn: {
    tagline: 'স্মার্ট শিখুন • আরও ভালো অনুশীলন করুন',
    study_mode: 'পড়াশোনা মোড',
    classes: 'ক্লাসসমূহ',
    reading_coach: 'রিডিং কোচ',
    vocabulary: 'শব্দভাণ্ডার',
    ask_doubt: 'প্রশ্ন জিজ্ঞাসা',
    revision: 'পুনরাবৃত্তি',
    exam_prep: 'পরীক্ষা প্রস্তুতি',
    ask_ai_tutor: 'AI শিক্ষককে জিজ্ঞাসা করুন',
    ask_ai: 'AI শিক্ষক',
    study_now: 'অধ্যয়ন করুন [শিখুন]',
    practice: 'অনুশীলন',
    mastery: 'দক্ষতা',
    min: 'মিনিট',
    mins: 'মিনিট',
    overall_mastery: 'বিষয় দক্ষতা স্তর',
    in_curriculum: 'এই পাঠ্যক্রমে',
    curriculum_chapters: 'পাঠ্যক্রম অধ্যায়',
    chapters: 'অধ্যায়',
    dashboard: 'ড্যাশবোর্ড',
    catalog: 'ক্যাটালগ',
    mock_tests: 'মক টেস্ট',
    login_onboard: '+ লগইন / যোগ দিন',
    switch_language: 'ভারতীয় ভাষা নির্বাচন করুন',
    languages_label: 'ভাষা',
    popular_languages: 'জনপ্রিয় ভাষাসমূহ',
    all_languages: 'সকল ভারতীয় ভাষা (২২টি সরকারি)',

    // Landing Page Hero
    hero_badge: 'দেশনা এআই লার্নিং হাব • ১ম থেকে ১১শ শ্রেণির জন্য',
    hero_languages_badge: '২২+ ভারতীয় ভাষা • বাংলা, हिन्दी, मराठी, ইত্যাদি',
    hero_headline_1: 'একটি সর্বাঙ্গীন AI শিক্ষা প্ল্যাটফর্ম।',
    hero_headline_2: 'প্রতিটি শ্রেণি। প্রতিটি বিষয়।',
    hero_headline_3: 'প্রতিটি শিক্ষার্থীর জন্য ব্যক্তিগতকৃত।',
    hero_description: '"স্মার্ট শিখুন। আরও ভালো অনুশীলন করুন। প্রতিদিন উন্নতি করুন।" ১ম শ্রেণির প্রাথমিক উচ্চারণ ও ব্যাকরণ থেকে ১১শ শ্রেণির বিশেষায়িত শাখা (CBSE, ICSE, স্টেট বোর্ড)—অভিযোজিত অনুশীলন, ইন্টারেক্টিভ রিডিং কোচ এবং সার্বক্ষণিক AI শিক্ষকের সাথে।',

    // Auth & Navigation
    portal_system_admin: 'সিস্টেম অ্যাডমিন',
    portal_student_login: 'শিক্ষার্থী রোল লগইন',
    portal_parent_login: 'অভিভাবক মোবাইল প্রবেশ',
    enter_admin_email: 'অ্যাডমিনিস্ট্রেটর ইমেল',
    enter_admin_password: 'পাসওয়ার্ড',
    enter_student_roll: 'শিক্ষার্থীর রোল কোড লিখুন (যেমন DESH-GR3-8821)',
    enter_student_name: 'শিক্ষার্থীর পুরো নাম',
    select_class_grade: 'শ্রেণি / গ্রেড নির্বাচন করুন',
    select_board: 'শিক্ষা বোর্ড নির্বাচন করুন',
    parent_whatsapp_phone: 'অভিভাবকের হোয়াটসঅ্যাপ নম্বর',
    login_as_student: 'শিক্ষার্থী হিসেবে লগইন করুন',
    register_new_student: 'নিবন্ধন করুন ও শেখা শুরু করুন',
    login_as_parent: 'অভিভাবক নম্বর যাচাই ও প্রবেশ',
    login_as_admin: 'অ্যাডমিন কনসোলে লগইন করুন',
    quick_demo_access: '✨ দ্রুত ডেমো প্রবেশ:',
    quick_demo_grade3: '👦 ৩য় শ্রেণি CBSE (অ্যালেক্স)',
    quick_demo_grade10: '👧 ১০ম শ্রেণি বোর্ড (সারা)',
    quick_demo_grade11: '🔬 ১১শ শ্রেণি বিজ্ঞান (রাহুল)',
    explore_all_classes: '📚 সব শ্রেণি অন্বেষণ করুন (১ম - ১১শ শ্রেণি)',
    start_learning_free: 'বিনামূল্যে AI অনুশীলন শুরু করুন',

    // Landing Page Sections
    curriculum_title: 'সম্পূর্ণ ১ম থেকে ১১শ শ্রেণির পাঠ্যক্রম নির্দেশিকা',
    curriculum_subtitle: 'সমস্ত ১১টি শ্রেণির বিষয়, অধ্যায়, ইন্টারেক্টিভ কুইজ এবং AI শিক্ষকের ব্যাখ্যা অন্বেষণ করুন।',
    features_title: 'স্মার্ট শিক্ষার জন্য শক্তিশালী AI সরঞ্জাম',
    features_subtitle: 'স্কুল শিক্ষার্থীদের শ্রেষ্ঠত্ব অর্জন, অনুপ্রাণিত থাকা এবং গভীর ধারণা গঠনের জন্য প্রয়োজনীয় সবকিছু।',
    feature_reading_coach_title: 'ইন্টারেক্টিভ AI রিডিং কোচ',
    feature_reading_coach_desc: 'রিয়েল-টাইম উচ্চারণ নির্দেশিকা, নির্ভুল পাঠ মূল্যায়ন, প্রতিটি শব্দের উচ্চারণ সহায়তা এবং গল্প বোঝার ক্ষমতা।',
    feature_doubt_title: 'তাৎক্ষণিক ২৪/৭ ধাপে ধাপে সন্দেহ সমাধানকারী',
    feature_doubt_desc: 'যেকোনো হোমওয়ার্কের ছবি তুলুন বা প্রশ্ন লিখুন। ধাপে ধাপে সোক্রেটিক নির্দেশিকা পান যা প্রকৃত উপলব্ধি গড়ে তোলে।',
    feature_revision_title: 'স্মার্ট স্পেসড রিপিটেশন রিভিশন ভল্ট',
    feature_revision_desc: 'যা শিখেছেন তা কখনোই ভুলবেন না। লেইটনার বক্স পদ্ধতি নিশ্চিত করে যে বিষয়গুলি স্থায়ী স্মৃতিতে সংরক্ষিত হয়।',
    feature_exam_title: 'বোর্ড ও প্রতিযোগিতামূলক পরীক্ষার প্রস্তুতি',
    feature_exam_desc: 'CBSE, ICSE এবং রাজ্য বোর্ডের জন্য অভিযোজিত মক টেস্ট, সময়সীমার প্রশ্ন এবং পারফরম্যান্স বিশ্লেষণ।',

    // Student Dashboard
    hello_greeting: 'নমস্কার',
    day_streak: 'দিনের ধারাবাহিকতা',
    streak_subtext: 'দৈনিক অধ্যয়নের অভ্যাস',
    mastery_points: 'দক্ষতা পয়েন্ট',
    points_subtext: 'অনুশীলনের মাধ্যমে অর্জিত',
    reading_speed: 'পড়ার গতি',
    speed_subtext: 'প্রতি মিনিটে শব্দ',
    words_mastered: 'আয়ত্ত করা শব্দ',
    vocab_subtext: 'শব্দভাণ্ডারে সংরক্ষিত',
    daily_study_plan: 'আপনার দৈনিক অধ্যয়ন পরিকল্পনা',
    daily_plan_desc: 'আপনার দক্ষতা এবং আসন্ন বিষয়ের উপর ভিত্তি করে ৩০ মিনিটের AI কাস্টমাইজড অনুশীলন।',
    time_target: 'দৈনিক লক্ষ্য',
    regenerate_plan: 'পরিকল্পনা পরিবর্তন',
    start_activity: 'কার্যক্রম শুরু করুন',
    completed: 'সম্পন্ন',
    continue_learning: 'শেখা চালিয়ে যান',
    all_subjects: 'সমস্ত বিষয়সমূহ',
    chapters_count: 'অধ্যায়',
    questions_count: 'প্রশ্নসমূহ',
    mastery_level: 'দক্ষতা',
    start_subject: 'বিষয় খুলুন',
    quick_practice: 'দ্রুত অনুশীলনী প্রশ্ন',
    due_revisions: 'রিভিশনের জন্য প্রস্তুত বিষয়',
    revise_now: 'এখনই রিভিশন করুন',
    recent_badges: 'আপনার অর্জন ও ব্যাজ',

    // Subject & Chapter View
    chapter_roadmap: 'অধ্যায় রোডম্যাপ ও অনুশীলন',
    learning_objectives: 'শেখার উদ্দেশ্যসমূহ',
    est_time: 'আনুমানিক সময়',
    minutes: 'মিনিট',
    start_chapter: 'অধ্যায় শুরু করুন',
    concept_notes: 'ধারণাগত নোট ও ব্যাখ্যা',
    practice_tab: 'অনুশীলন ও কুইজ',
    summary_tab: 'দ্রুত সারসংক্ষেপ ও সূত্র',
    key_takeaways: 'মূল বিষয় ও সূত্রাবলী',
    topics_in_chapter: 'এই অধ্যায়ের বিষয়সমূহ',
    difficulty: 'কঠিনতা',
    easy: 'সহজ',
    medium: 'মাঝারি',
    hard: 'কঠিন',
    advanced: 'উন্নত',

    // Practice Questions
    question_label: 'প্রশ্ন',
    of_label: '/',
    check_answer: 'উত্তর পরীক্ষা করুন',
    next_question: 'পরবর্তী প্রশ্ন',
    previous_question: 'পূর্ববর্তী প্রশ্ন',
    show_hint: 'ইঙ্গিত প্রয়োজন?',
    hide_hint: 'ইঙ্গিত লুকান',
    explanation_title: 'ধাপে ধাপে ব্যাখ্যা',
    correct_feedback: 'সঠিক উত্তর! চমৎকার কাজ! 🌟',
    incorrect_feedback: 'সঠিক হয়নি। আসুন সঠিক ধারণাটি বুঝে নিই:',
    practice_completed_title: 'অনুশীলন সেশন সম্পন্ন হয়েছে! 🎉',
    your_score: 'আপনার স্কোর',
    points_earned: 'অর্জিত পয়েন্ট',
    retake_quiz: 'আবার অনুশীলন করুন',
    next_chapter: 'পরবর্তী বিষয়ে এগিয়ে যান',
    ask_ai_explain: 'AI শিক্ষককে বিস্তারিত বোঝাতে বলুন',

    // General
    search_placeholder: 'বিষয়, অধ্যায়, প্রশ্ন খুঁজুন...',
    all_grades: 'সমস্ত শ্রেণি',
    grade: 'শ্রেণি',
    board: 'বোর্ড',
    stream: 'শাখা',
    back_to_dashboard: '← ড্যাশবোর্ডে ফিরে যান',
    back_to_subjects: '← বিষয়সমূহে ফিরে যান',
  },

  hi: {
    tagline: 'स्मार्ट सीखें • बेहतर अभ्यास करें',
    study_mode: 'अध्ययन मोड',
    classes: 'कक्षाएं',
    reading_coach: 'रीडिंग कोच',
    vocabulary: 'शब्दावली',
    ask_doubt: 'डाउट पूछें',
    revision: 'रिवीजन',
    exam_prep: 'परीक्षा तैयारी',
    ask_ai_tutor: 'AI ट्यूटर से पूछें',
    ask_ai: 'AI से पूछें',
    study_now: 'अध्ययन करें [सीखें]',
    practice: 'अभ्यास',
    mastery: 'दक्षता',
    min: 'मिनट',
    mins: 'मिनट',
    overall_mastery: 'विषय दक्षता स्तर',
    in_curriculum: 'इस पाठ्यक्रम में',
    curriculum_chapters: 'पाठ्यक्रम अध्याय',
    chapters: 'अध्याय',
    dashboard: 'डैशबोर्ड',
    catalog: 'कैटलॉग',
    mock_tests: 'मॉक टेस्ट',
    login_onboard: '+ लॉगिन / जुड़ें',
    switch_language: 'भारतीय भाषा चुनें',
    languages_label: 'भाषाएं',
    popular_languages: 'प्रमुख भाषाएं',
    all_languages: 'सभी भारतीय भाषाएं (२२ आधिकारिक)',

    hero_badge: 'देशना एआई लर्निंग हब • कक्षा १ से ११ के लिए',
    hero_languages_badge: '२२+ भारतीय भाषाएं • हिन्दी, বাংলা, मराठी, आदि',
    hero_headline_1: 'एक संपूर्ण AI शिक्षण मंच।',
    hero_headline_2: 'हर कक्षा। हर विषय।',
    hero_headline_3: 'हर छात्र के लिए व्यक्तिगत अनुकूलन।',
    hero_description: '"स्मार्ट सीखें। बेहतर अभ्यास करें। हर दिन आगे बढ़ें।" कक्षा १ के बुनियादी ध्वनिविज्ञान से लेकर कक्षा ११ के विशिष्ट संकायों (CBSE, ICSE, स्टेट बोर्ड)—अनुकूली अभ्यास, इंटरैक्टिव रीडिंग कोच और २४/७ AI ट्यूटर के साथ।',

    portal_system_admin: 'सिस्टम एडमिन',
    portal_student_login: 'छात्र रोल कोड लॉगिन',
    portal_parent_login: 'अभिभावक मोबाइल प्रवेश',
    enter_admin_email: 'व्यवस्थापक ईमेल',
    enter_admin_password: 'पासवर्ड',
    enter_student_roll: 'छात्र का रोल कोड दर्ज करें (जैसे DESH-GR3-8821)',
    enter_student_name: 'छात्र का पूरा नाम',
    select_class_grade: 'कक्षा / ग्रेड चुनें',
    select_board: 'शिक्षा बोर्ड चुनें',
    parent_whatsapp_phone: 'अभिभावक व्हाट्सएप नंबर',
    login_as_student: 'छात्र के रूप में लॉगिन करें',
    register_new_student: 'पंजीकरण करें और सीखना शुरू करें',
    login_as_parent: 'अभिभावक नंबर सत्यापित करें और प्रवेश करें',
    login_as_admin: 'एडमिन कंसोल में लॉगिन करें',
    quick_demo_access: '✨ त्वरित डेमो प्रवेश:',
    quick_demo_grade3: '👦 कक्षा ३ CBSE (एलेक्स)',
    quick_demo_grade10: '👧 कक्षा १० बोर्ड (सारा)',
    quick_demo_grade11: '🔬 कक्षा ११ विज्ञान (राहुल)',
    explore_all_classes: '📚 सभी कक्षाएं देखें (कक्षा १ - ११)',
    start_learning_free: 'निःशुल्क AI अभ्यास शुरू करें',

    curriculum_title: 'सम्पूर्ण कक्षा १ से ११ पाठ्यक्रम सूची',
    curriculum_subtitle: 'सभी ११ कक्षाओं के विषय, अध्याय, इंटरैक्टिव प्रश्नोत्तरी और AI ट्यूटर स्पष्टीकरण देखें।',
    features_title: 'स्मार्ट सीखने के लिए शक्तिशाली AI उपकरण',
    features_subtitle: 'स्कूली छात्रों के उत्कृष्ट प्रदर्शन और गहरी वैचारिक स्पष्टता के लिए सब कुछ।',
    feature_reading_coach_title: 'इंटरैक्टिव AI रीडिंग कोच',
    feature_reading_coach_desc: 'सटीक उच्चारण मार्गदर्शन, पठन मूल्यांकन, शब्द-दर-शब्द ध्वनि सहायता और समझ विकास।',
    feature_doubt_title: 'त्वरित २४/७ चरण-दर-चरण डाउट सॉल्वर',
    feature_doubt_desc: 'होमवर्क का फोटो खींचें या प्रश्न टाइप करें। वास्तविक समझ विकसित करने वाले चरण-दर-चरण उत्तर पाएं।',
    feature_revision_title: 'स्मार्ट स्पेस्ड रिपीटिशन रिवीजन वॉल्ट',
    feature_revision_desc: 'जो सीखा है उसे कभी न भूलें। लीटनर बॉक्स विधि विषयों को स्थायी स्मृति में बनाए रखती है।',
    feature_exam_title: 'बोर्ड और प्रतियोगी परीक्षा तैयारी',
    feature_exam_desc: 'CBSE, ICSE और राज्य बोर्डों के लिए अनुकूली मॉक टेस्ट, समयबद्ध प्रश्न और विस्तृत प्रदर्शन विश्लेषण।',

    hello_greeting: 'नमस्ते',
    day_streak: 'दिनों की लड़ी',
    streak_subtext: 'दैनिक अध्ययन आदत',
    mastery_points: 'दक्षता अंक',
    points_subtext: 'अभ्यास द्वारा अर्जित',
    reading_speed: 'पठन गति',
    speed_subtext: 'शब्द प्रति मिनट',
    words_mastered: 'कंठस्थ शब्द',
    vocab_subtext: 'शब्दावली वॉल्ट में',
    daily_study_plan: 'आपकी दैनिक अध्ययन योजना',
    daily_plan_desc: 'आपकी दक्षता और आगामी विषयों पर आधारित ३० मिनट का AI अनुकूलित अभ्यास।',
    time_target: 'दैनिक लक्ष्य',
    regenerate_plan: 'योजना बदलें',
    start_activity: 'गतिविधि शुरू करें',
    completed: 'पूर्ण',
    continue_learning: 'सीखना जारी रखें',
    all_subjects: 'सभी विषय',
    chapters_count: 'अध्याय',
    questions_count: 'प्रश्न',
    mastery_level: 'दक्षता',
    start_subject: 'विषय खोलें',
    quick_practice: 'त्वरित अभ्यास प्रश्न',
    due_revisions: 'रिवीजन के लिए लंबित विषय',
    revise_now: 'अभी रिवीजन करें',
    recent_badges: 'आपकी उपलब्धियां और बैज',

    chapter_roadmap: 'अध्याय रोडमैप और अभ्यास',
    learning_objectives: 'सीखने के उद्देश्य',
    est_time: 'अनुमानित समय',
    minutes: 'मिनट',
    start_chapter: 'अध्याय शुरू करें',
    concept_notes: 'संकल्पना नोट्स और स्पष्टीकरण',
    practice_tab: 'अभ्यास और प्रश्नोत्तरी',
    summary_tab: 'त्वरित सारांश और सूत्र',
    key_takeaways: 'मुख्य बिंदु और सूत्र',
    topics_in_chapter: 'इस अध्याय के विषय',
    difficulty: 'कठिनाई',
    easy: 'सरल',
    medium: 'मध्यम',
    hard: 'कठिन',
    advanced: 'उन्नत',

    question_label: 'प्रश्न',
    of_label: 'का',
    check_answer: 'उत्तर जांचें',
    next_question: 'अगला प्रश्न',
    previous_question: 'पिछला प्रश्न',
    show_hint: 'संकेत चाहिए?',
    hide_hint: 'संकेत छिपाएं',
    explanation_title: 'चरण-दर-चरण स्पष्टीकरण',
    correct_feedback: 'सही उत्तर! बहुत बढ़िया! 🌟',
    incorrect_feedback: 'सही नहीं हुआ। आइए सही संकल्पना को समझें:',
    practice_completed_title: 'अभ्यास सत्र संपन्न! 🎉',
    your_score: 'आपका स्कोर',
    points_earned: 'अर्जित अंक',
    retake_quiz: 'पुनः अभ्यास करें',
    next_chapter: 'अगले विषय पर जाएं',
    ask_ai_explain: 'AI ट्यूटर से विस्तार से समझाने को कहें',

    search_placeholder: 'विषय, अध्याय, प्रश्न खोजें...',
    all_grades: 'सभी कक्षाएं',
    grade: 'कक्षा',
    board: 'बोर्ड',
    stream: 'संकाय',
    back_to_dashboard: '← डैशबोर्ड पर वापस जाएं',
    back_to_subjects: '← विषयों पर वापस जाएं',
  },

  mr: {
    tagline: 'हुशारीने शिका • उत्तम सराव करा',
    study_mode: 'अभ्यास मोड',
    classes: 'वर्ग / इयत्ता',
    reading_coach: 'वाचन मार्गदर्शक',
    vocabulary: 'शब्दसंग्रह',
    ask_doubt: 'शंका विचारा',
    revision: 'पुनरावलोकन',
    exam_prep: 'परीक्षा तयारी',
    ask_ai_tutor: 'AI मार्गदर्शकास विचारा',
    login_onboard: '+ लॉगिन / नोंदणी',
    switch_language: 'भारतीय भाषा निवडा',
    languages_label: 'भाषा',
    popular_languages: 'प्रमुख भाषा',
    all_languages: 'सर्व भारतीय भाषा (२२ अधिकृत)',

    hero_badge: 'देशना एआय लर्निंग हब • इयत्ता १ ली ते ११ वी',
    hero_languages_badge: '२२+ भारतीय भाषा • मराठी, हिन्दी, বাংলা, इत्यादी',
    hero_headline_1: 'एक परिपूर्ण AI शिक्षण मंच.',
    hero_headline_2: 'प्रत्येक इयत्ता. प्रत्येक विषय.',
    hero_headline_3: 'प्रत्येक विद्यार्थ्यासाठी वैयक्तिकृत.',
    hero_description: '"हुशारीने शिका. उत्तम सराव करा. दररोज प्रगती करा." इयत्ता १ ली च्या मूलभूत वाचनापासून ते इयत्ता ११ वी च्या विज्ञान, वाणिज्य व कला शाखांपर्यंत—अनुकूल सराव आणि २४/७ AI मार्गदर्शकासह.',

    portal_system_admin: 'प्रणाली प्रशासक',
    portal_student_login: 'विद्यार्थी हजेरी क्रमांक लॉगिन',
    portal_parent_login: 'पालक मोबाइल प्रवेश',
    enter_admin_email: 'प्रशासक ईमेल',
    enter_admin_password: 'पासवर्ड',
    enter_student_roll: 'विद्यार्थ्याचा कोड टाका (उदा. DESH-GR3-8821)',
    enter_student_name: 'विद्यार्थ्याचे पूर्ण नाव',
    select_class_grade: 'इयत्ता निवडा',
    select_board: 'शिक्षण मंडळ निवडा',
    parent_whatsapp_phone: 'पालकांचा व्हॉट्सॲप नंबर',
    login_as_student: 'विद्यार्थी म्हणून लॉगिन करा',
    register_new_student: 'नोंदणी करा व शिकणे सुरू करा',
    login_as_parent: 'पालक क्रमांक पडताळा व प्रवेश करा',
    login_as_admin: 'अॅडमिन कन्सोलमध्ये लॉगिन करा',
    quick_demo_access: '✨ जलद डेमो प्रवेश:',
    quick_demo_grade3: '👦 इयत्ता ३ री CBSE (ॲलेक्स)',
    quick_demo_grade10: '👧 इयत्ता १० वी बोर्ड (सारा)',
    quick_demo_grade11: '🔬 इयत्ता ११ वी विज्ञान (राहुल)',
    explore_all_classes: '📚 सर्व इयत्ता पहा (१ ली - ११ वी)',
    start_learning_free: 'विनामूल्य AI सराव सुरू करा',

    hello_greeting: 'नमस्कार',
    day_streak: 'दैनंदिन सातत्य',
    streak_subtext: 'दररोज अभ्यासाची सवय',
    mastery_points: 'प्राविण्य गुण',
    points_subtext: 'सरावाद्वारे मिळवले',
    reading_speed: 'वाचन गती',
    speed_subtext: 'शब्द प्रति मिनिट',
    words_mastered: 'आत्मसात शब्द',
    vocab_subtext: 'शब्दसंग्रहामध्ये',
    daily_study_plan: 'तुमची दैनंदिन अभ्यास योजना',
    daily_plan_desc: 'तुमच्या कौशल्यावर आधारित ३० मिनिटांचा AI अनुकूलित सराव.',
    time_target: 'दैनंदिन उद्दिष्ट',
    regenerate_plan: 'योजना बदला',
    start_activity: 'सुरू करा',
    completed: 'पूर्ण झाले',
    continue_learning: 'शिकणे सुरू ठेवा',
    all_subjects: 'सर्व विषय',
    chapters_count: 'धडे / प्रकरणे',
    questions_count: 'प्रश्न',
    mastery_level: 'प्राविण्य',
    start_subject: 'विषय उघडा',
    quick_practice: 'जलद सराव प्रश्न',
    due_revisions: 'पुनरावलोकनासाठी प्रलंबित विषय',
    revise_now: 'आता पुनरावलोकन करा',
    recent_badges: 'तुमची यशोगाथा व पदके',

    chapter_roadmap: 'प्रकरण आराखडा आणि सराव',
    learning_objectives: 'शिकण्याची उद्दिष्टे',
    est_time: 'अपेक्षित वेळ',
    minutes: 'मिनिटे',
    start_chapter: 'प्रकरण सुरू करा',
    concept_notes: 'संकल्पना व स्पष्टीकरण',
    practice_tab: 'सराव व प्रश्नमंजुषा',
    summary_tab: 'थोडक्यात सारांश व सूत्रे',
    key_takeaways: 'महत्त्वाचे मुद्दे व सूत्रे',
    topics_in_chapter: 'या प्रकरणातील घटक',
    difficulty: 'काठिण्य पातळी',
    easy: 'सोपे',
    medium: 'मध्यम',
    hard: 'कठीण',
    advanced: 'प्रगत',

    question_label: 'प्रश्न',
    of_label: 'पैकी',
    check_answer: 'उत्तर तपासा',
    next_question: 'पुढील प्रश्न',
    previous_question: 'मागील प्रश्न',
    show_hint: 'सूचना हवी आहे का?',
    hide_hint: 'सूचना लपवा',
    explanation_title: 'सविस्तर स्पष्टीकरण',
    correct_feedback: 'अचूक उत्तर! खूप छान! 🌟',
    incorrect_feedback: 'उत्तर चुकले. चला योग्य संकल्पना समजून घेऊया:',
    practice_completed_title: 'सराव सत्र पूर्ण झाले! 🎉',
    your_score: 'तुमचे गुण',
    points_earned: 'मिळवलेले गुण',
    retake_quiz: 'पुन्हा सराव करा',
    next_chapter: 'पुढील घटकाकडे जा',
    ask_ai_explain: 'AI मार्गदर्शकाकडून स्पष्टीकरण मागा',

    search_placeholder: 'विषय, धडे, प्रश्न शोधा...',
    all_grades: 'सर्व इयत्ता',
    grade: 'इयत्ता',
    board: 'मंडळ',
    stream: 'शाखा',
    back_to_dashboard: '← डॅशबोर्डवर परत जा',
    back_to_subjects: '← विषयांवर परत जा',
  },

  te: {
    tagline: 'తెలివిగా నేర్చుకోండి • మెరుగ్గా సాధన చేయండి',
    study_mode: 'అధ్యయన మోడ్',
    classes: 'తరగతులు',
    reading_coach: 'రీడింగ్ కోచ్',
    vocabulary: 'పదజాలం',
    ask_doubt: 'సందేహం అడగండి',
    revision: 'పునశ్చరణ',
    exam_prep: 'పరీక్షల సన్నద్ధత',
    ask_ai_tutor: 'AI ట్యూటర్‌ను అడగండి',
    login_onboard: '+ లాగిన్ / చేరండి',
    switch_language: 'భారతీయ భాషను ఎంచుకోండి',
    languages_label: 'భాషలు',
    popular_languages: 'ప్రసిద్ధ భాషలు',
    all_languages: 'అన్ని భారతీయ భాషలు (22 అధికారిక)',

    hero_badge: 'దేశ్నా AI లెర్నింగ్ హబ్ • 1 నుండి 11వ తరగతి విద్యార్థులకు',
    hero_languages_badge: '22+ భారతీయ భాషలు • తెలుగు, हिन्दी, বাংলা, మొదలైనవి',
    hero_headline_1: 'సమగ్ర AI లెర్నింగ్ ప్లాట్‌ఫారమ్.',
    hero_headline_2: 'ప్రతి తరగతి. ప్రతి సబ్జెక్ట్.',
    hero_headline_3: 'ప్రతి విద్యార్థికి వ్యక్తిగతీకరించబడింది.',
    hero_description: '"తెలివిగా నేర్చుకోండి. మెరుగ్గా సాధన చేయండి. ప్రతిరోజూ ఎదగండి." 1వ తరగతి ప్రాథమిక విద్య నుండి 11వ తరగతి ప్రత్యేక స్ట్రీమ్‌ల వరకు—అనుకూల ప్రాక్టీస్ మరియు 24/7 AI ట్యూటర్‌తో.',

    portal_system_admin: 'సిస్టమ్ అడ్మిన్',
    portal_student_login: 'విద్యార్థి రోల్ లాగిన్',
    portal_parent_login: 'తల్లిదండ్రుల మొబైల్ ప్రవేశం',
    enter_admin_email: 'అడ్మినిస్ట్రేటర్ ఈమెయిల్',
    enter_admin_password: 'పాస్‌వర్డ్',
    enter_student_roll: 'విద్యార్థి రోల్ కోడ్ నమోదు చేయండి',
    enter_student_name: 'విద్యార్థి పూర్తి పేరు',
    select_class_grade: 'తరగతిని ఎంచుకోండి',
    select_board: 'విద్యా బోర్డును ఎంచుకోండి',
    parent_whatsapp_phone: 'తల్లిదండ్రుల వాట్సాప్ నంబర్',
    login_as_student: 'విద్యార్థిగా లాగిన్ అవ్వండి',
    register_new_student: 'నమోదు చేసుకోండి & నేర్చుకోవడం ప్రారంభించండి',
    login_as_parent: 'తల్లిదండ్రుల నంబర్ ధృవీకరించి లాగిన్ అవ్వండి',
    login_as_admin: 'అడ్మిన్ కన్సోల్‌లోకి లాగిన్ అవ్వండి',
    quick_demo_access: '✨ త్వరిత డెమో యాక్సెస్:',
    quick_demo_grade3: '👦 3వ తరగతి CBSE (అలెక్స్)',
    quick_demo_grade10: '👧 10వ తరగతి బోర్డు (సారా)',
    quick_demo_grade11: '🔬 11వ తరగతి సైన్స్ (రాహుల్)',
    explore_all_classes: '📚 అన్ని తరగతులను అన్వేషించండి (1 - 11)',
    start_learning_free: 'ఉచిత AI ప్రాక్టీస్ ప్రారంభించండి',

    hello_greeting: 'నమస్కారం',
    day_streak: 'రోజువారీ స్ట్రీక్',
    streak_subtext: 'రోజువారీ అధ్యయన అలవాటు',
    mastery_points: 'నైపుణ్య పాయింట్లు',
    points_subtext: 'సాధన ద్వారా సంపాదించినవి',
    reading_speed: 'పఠన వేగం',
    speed_subtext: 'నిమిషానికి పదాలు',
    words_mastered: 'నేర్చుకున్న పదాలు',
    vocab_subtext: 'పదజాలంలో నిల్వ చేయబడినవి',
    daily_study_plan: 'మీ రోజువారీ అధ్యయన ప్రణాళిక',
    daily_plan_desc: 'మీ నైపుణ్యం ఆధారంగా 30 నిమిషాల AI అనుకూలీకరించిన ప్రాక్టీస్.',
    time_target: 'రోజువారీ లక్ష్యం',
    regenerate_plan: 'ప్రణాళిక మార్చండి',
    start_activity: 'ప్రారంభించండి',
    completed: 'పూర్తయింది',
    continue_learning: 'నేర్చుకోవడం కొనసాగించండి',
    all_subjects: 'అన్ని సబ్జెక్టులు',
    chapters_count: 'అధ్యాయాలు',
    questions_count: 'ప్రశ్నలు',
    mastery_level: 'నైపుణ్యం',
    start_subject: 'సబ్జెక్ట్ తెరవండి',
    quick_practice: 'త్వరిత ప్రాక్టీస్ ప్రశ్నలు',
    due_revisions: 'పునశ్చరణ చేయాల్సిన అంశాలు',
    revise_now: 'ఇప్పుడే పునశ్చరణ చేయండి',
    recent_badges: 'మీ విజయాలు & బ్యాడ్జ్‌లు',

    chapter_roadmap: 'అధ్యాయం రోడ్‌మ్యాప్ & ప్రాక్టీస్',
    learning_objectives: 'అభ్యాస లక్ష్యాలు',
    est_time: 'అంచనా సమయం',
    minutes: 'నిమిషాలు',
    start_chapter: 'అధ్యాయాన్ని ప్రారంభించండి',
    concept_notes: 'కాన్సెప్ట్ నోట్స్ & వివరణలు',
    practice_tab: 'ప్రాక్టీస్ & క్విజ్',
    summary_tab: 'సారాంశం & సూత్రాలు',
    key_takeaways: 'ముఖ్యమైన అంశాలు & సూత్రాలు',
    topics_in_chapter: 'ఈ అధ్యాయంలోని అంశాలు',
    difficulty: 'కఠినత స్థాయి',
    easy: 'సులభం',
    medium: 'మధ్యస్థం',
    hard: 'కఠినం',
    advanced: 'ఉన్నత స్థాయి',

    question_label: 'ప్రశ్న',
    of_label: '/',
    check_answer: 'సమాధానం తనిఖీ చేయండి',
    next_question: 'తదుపరి ప్రశ్న',
    previous_question: 'మునుపటి ప్రశ్న',
    show_hint: 'సూచన కావాలా?',
    hide_hint: 'సూచన దాచు',
    explanation_title: 'దశలవారీ వివరణ',
    correct_feedback: 'సరైన సమాధానం! అద్భుతం! 🌟',
    incorrect_feedback: 'సరైనది కాదు. కాన్సెప్ట్‌ను అర్థం చేసుకుందాం:',
    practice_completed_title: 'ప్రాక్టీస్ పూర్తయింది! 🎉',
    your_score: 'మీ స్కోరు',
    points_earned: 'పొందిన పాయింట్లు',
    retake_quiz: 'మళ్లీ సాధన చేయండి',
    next_chapter: 'తదుపరి అంశానికి వెళ్లండి',
    ask_ai_explain: 'AI ట్యూటర్‌ను వివరంగా వివరించమని అడగండి',

    search_placeholder: 'సబ్జెక్టులు, అధ్యాయాలు, ప్రశ్నలు శోధించండి...',
    all_grades: 'అన్ని తరగతులు',
    grade: 'తరగతి',
    board: 'బోర్డు',
    stream: 'స్ట్రీమ్',
    back_to_dashboard: '← డ్యాష్‌బోర్డ్‌కి తిరిగి వెళ్ళండి',
    back_to_subjects: '← సబ్జెక్టులకు తిరిగి వెళ్ళండి',
  },

  ta: {
    tagline: 'புத்திசாலித்தனமாக கற்போம் • சிறப்பாக பயிற்சி செய்வோம்',
    study_mode: 'படிப்பு முறை',
    classes: 'வகுப்புகள்',
    reading_coach: 'வாசிப்பு பயிற்றுவிப்பாளர்',
    vocabulary: 'சொற்களஞ்சியம்',
    ask_doubt: 'சந்தேகம் கேட்க',
    revision: 'மீள்பார்வை',
    exam_prep: 'தேர்வு தயாரிப்பு',
    ask_ai_tutor: 'AI ஆசிரியரிடம் கேளுங்கள்',
    login_onboard: '+ உள்நுழைவு / பதிவு',
    switch_language: 'இந்திய மொழியைத் தேர்ந்தெடுக்கவும்',
    languages_label: 'மொழிகள்',
    popular_languages: 'பிரபலமான மொழிகள்',
    all_languages: 'அனைத்து இந்திய மொழிகள் (22 அதிகாரப்பூர்வ)',

    hero_badge: 'தேஷ்னா AI கற்றல் மையம் • 1 முதல் 11 ஆம் வகுப்பு வரை',
    hero_languages_badge: '22+ இந்திய மொழிகள் • தமிழ், हिन्दी, বাংলা, போன்றவை',
    hero_headline_1: 'முழுமையான AI கற்றல் தளம்.',
    hero_headline_2: 'ஒவ்வொரு வகுப்பு. ஒவ்வொரு பாடம்.',
    hero_headline_3: 'ஒவ்வொரு மாணவருக்கும் பிரத்யேகமானது.',
    hero_description: '"புத்திசாலித்தனமாக கற்போம். சிறப்பாக பயிற்சி செய்வோம். தினமும் வளர்வோம்." 1 ஆம் வகுப்பு அடிப்படை முதல் 11 ஆம் வகுப்பு பாடப்பிரிவுகள் வரை—பயிற்சி மற்றும் 24/7 AI ஆசிரியருடன்.',

    portal_system_admin: 'கணினி நிர்வாகி',
    portal_student_login: 'மாணவர் ரோல் எண் உள்நுழைவு',
    portal_parent_login: 'பெற்றோர் மொபைல் அணுகல்',
    enter_admin_email: 'நிர்வாக மின்னஞ்சல்',
    enter_admin_password: 'கடவுச்சொல்',
    enter_student_roll: 'மாணவர் குறியீட்டை உள்ளிடவும்',
    enter_student_name: 'மாணவர் முழு பெயர்',
    select_class_grade: 'வகுப்பைத் தேர்ந்தெடுக்கவும்',
    select_board: 'கல்வி வாரியத்தைத் தேர்ந்தெடுக்கவும்',
    parent_whatsapp_phone: 'பெற்றோர் வாட்ஸ்அப் எண்',
    login_as_student: 'மாணவராக உள்நுழைக',
    register_new_student: 'பதிவு செய்து கற்கத் தொடங்குங்கள்',
    login_as_parent: 'பெற்றோர் எண்ணை சரிபார்த்து உள்நுழைக',
    login_as_admin: 'நிர்வாக தளத்தில் உள்நுழைக',
    quick_demo_access: '✨ விரைவு டெமோ:',
    quick_demo_grade3: '👦 3 ஆம் வகுப்பு CBSE (அலெக்ஸ்)',
    quick_demo_grade10: '👧 10 ஆம் வகுப்பு வாரியம் (சாரா)',
    quick_demo_grade11: '🔬 11 ஆம் வகுப்பு அறிவியல் (ராகுல்)',
    explore_all_classes: '📚 அனைத்து வகுப்புகளையும் காண்க (1 - 11)',
    start_learning_free: 'இலவச AI பயிற்சியைத் தொடங்குங்கள்',

    hello_greeting: 'வணக்கம்',
    day_streak: 'தொடர் நாட்கள்',
    streak_subtext: 'தினசரி படிப்பு பழக்கம்',
    mastery_points: 'திறன் புள்ளிகள்',
    points_subtext: 'பயிற்சி மூலம் ஈட்டப்பட்டது',
    reading_speed: 'வாசிப்பு வேகம்',
    speed_subtext: 'நிமிடத்திற்கு சொற்கள்',
    words_mastered: 'கற்றறிந்த சொற்கள்',
    vocab_subtext: 'சொற்களஞ்சியத்தில் உள்ளது',
    daily_study_plan: 'உங்கள் தினசரி படிப்பு திட்டம்',
    daily_plan_desc: 'உங்கள் திறனுக்கு ஏற்ப 30 நிமிட AI தனிப்பயனாக்கப்பட்ட பயிற்சி.',
    time_target: 'தினசரி இலக்கு',
    regenerate_plan: 'திட்டத்தை மாற்று',
    start_activity: 'தொடங்கு',
    completed: 'முடிந்தது',
    continue_learning: 'தொடர்ந்து கற்கவும்',
    all_subjects: 'அனைத்து பாடங்கள்',
    chapters_count: 'அத்தியாயங்கள்',
    questions_count: 'கேள்விகள்',
    mastery_level: 'திறன் நிலை',
    start_subject: 'பாடத்தை திறக்கவும்',
    quick_practice: 'விரைவு பயிற்சி கேள்விகள்',
    due_revisions: 'மீள்பார்வை செய்ய வேண்டியவை',
    revise_now: 'இப்போதே மீள்பார்வை செய்க',
    recent_badges: 'உங்கள் சாதனைகள் & பதக்கங்கள்',

    chapter_roadmap: 'அத்தியாய திட்டம் & பயிற்சி',
    learning_objectives: 'கற்றல் நோக்கங்கள்',
    est_time: 'மதிப்பிடப்பட்ட நேரம்',
    minutes: 'நிமிடங்கள்',
    start_chapter: 'அத்தியாயத்தைத் தொடங்கு',
    concept_notes: 'பாட குறிப்புகள் & விளக்கம்',
    practice_tab: 'பயிற்சி & வினாடி வினா',
    summary_tab: 'சுருக்கம் & சூத்திரங்கள்',
    key_takeaways: 'முக்கிய குறிப்புகள் & சூத்திரங்கள்',
    topics_in_chapter: 'இந்த அத்தியாயத்தின் தலைப்புகள்',
    difficulty: 'சிரமம்',
    easy: 'எளிது',
    medium: 'நடுத்தரம்',
    hard: 'கடினம்',
    advanced: 'மேம்பட்டது',

    question_label: 'கேள்வி',
    of_label: '/',
    check_answer: 'விடையைச் சரிபார்க்கவும்',
    next_question: 'அடுத்த கேள்வி',
    previous_question: 'முந்தைய கேள்வி',
    show_hint: 'குறிப்பு தேவையா?',
    hide_hint: 'குறிப்பை மறை',
    explanation_title: 'படி படியான விளக்கம்',
    correct_feedback: 'சரியான விடை! அருமை! 🌟',
    incorrect_feedback: 'சரியாக இல்லை. சரியான விளக்கத்தை அறிவோம்:',
    practice_completed_title: 'பயிற்சி முடிந்தது! 🎉',
    your_score: 'உங்கள் மதிப்பெண்',
    points_earned: 'ஈட்டிய புள்ளிகள்',
    retake_quiz: 'மீண்டும் பயிற்சி செய்க',
    next_chapter: 'அடுத்த தலைப்புக்கு செல்லவும்',
    ask_ai_explain: 'AI ஆசிரியரிடம் விளக்கம் கேட்கவும்',

    search_placeholder: 'பாடங்கள், அத்தியாயங்கள், கேள்விகளைத் தேடுங்கள்...',
    all_grades: 'அனைத்து வகுப்புகள்',
    grade: 'வகுப்பு',
    board: 'வாரியம்',
    stream: 'பிரிவு',
    back_to_dashboard: '← முதன்மைப் பக்கத்திற்குச் செல்',
    back_to_subjects: '← பாடங்களுக்குச் செல்',
  },

  gu: {
    tagline: 'હોશિયારીથી શીખો • શ્રેષ્ઠ પ્રેક્ટિસ કરો',
    study_mode: 'અભ્યાસ મોડ',
    classes: 'વર્ગો',
    reading_coach: 'વાંચન કોચ',
    vocabulary: 'શબ્દભંડોળ',
    ask_doubt: 'શંકા પૂછો',
    revision: 'પુનરાવર્તન',
    exam_prep: 'પરીક્ષા તૈયારી',
    ask_ai_tutor: 'AI ટ્યુટરને પૂછો',
    login_onboard: '+ લૉગિન / જોડાઓ',
    switch_language: 'ભારતીય ભાષા પસંદ કરો',
    languages_label: 'ભાષાઓ',
    popular_languages: 'મુખ્ય ભાષાઓ',
    all_languages: 'તમામ ભારતીય ભાષાઓ (૨૨ માન્ય)',

    hero_badge: 'દેશના AI લર્નિંગ હબ • ધોરણ ૧ થી ૧૧ માટે',
    hero_languages_badge: '૨૨+ ભારતીય ભાષાઓ • ગુજરાતી, हिन्दी, বাংলা, વગેરે',
    hero_headline_1: 'એક સંપૂર્ણ AI લર્નિંગ પ્લેટફોર્મ.',
    hero_headline_2: 'દરેક ધોરણ. દરેક વિષય.',
    hero_headline_3: 'દરેક વિદ્યાર્થી માટે વ્યક્તિગત અનુકૂલન.',
    hero_description: '"હોશિયારીથી શીખો. શ્રેષ્ઠ પ્રેક્ટિસ કરો. દરરોજ પ્રગતિ કરો." ધોરણ ૧ ના પાયાના શિક્ષણથી લઈને ધોરણ ૧૧ ના વિષયો સુધી—અનુકૂલનશીલ પ્રેક્ટિસ અને ૨૪/૭ AI ટ્યુટર સાથે.',

    portal_system_admin: 'સિસ્ટમ એડમિન',
    portal_student_login: 'વિદ્યાર્થી રોલ કોડ લૉગિન',
    portal_parent_login: 'વાલી મોબાઈલ પ્રવેશ',
    enter_admin_email: 'એડમિનિસ્ટ્રેટર ઈમેલ',
    enter_admin_password: 'પાસવર્ડ',
    enter_student_roll: 'વિદ્યાર્થી રોલ કોડ દાખલ કરો',
    enter_student_name: 'વિદ્યાર્થીનું પૂરું નામ',
    select_class_grade: 'ધોરણ પસંદ કરો',
    select_board: 'શિક્ષણ બોર્ડ પસંદ કરો',
    parent_whatsapp_phone: 'વાલીનો વોટ્સએપ નંબર',
    login_as_student: 'વિદ્યાર્થી તરીકે લૉગિન કરો',
    register_new_student: 'નોંધણી કરો અને શીખવાનું શરૂ કરો',
    login_as_parent: 'વાલી નંબર ચકાસો અને પ્રવેશ કરો',
    login_as_admin: 'એડમિન કન્સોલમાં લૉગિન કરો',
    quick_demo_access: '✨ ઝડપી ડેમો:',
    quick_demo_grade3: '👦 ધોરણ ૩ CBSE (એલેક્સ)',
    quick_demo_grade10: '👧 ધોરણ ૧૦ બોર્ડ (સારા)',
    quick_demo_grade11: '🔬 ધોરણ ૧૧ સાયન્સ (રાહુલ)',
    explore_all_classes: '📚 તમામ ધોરણો જુઓ (ધોરણ ૧ - ૧૧)',
    start_learning_free: 'મફત AI પ્રેક્ટિસ શરૂ કરો',

    hello_greeting: 'નમસ્તે',
    day_streak: 'દૈનિક સાતત્ય',
    streak_subtext: 'દરરોજ અભ્યાસની ટેવ',
    mastery_points: 'નિપુણતા પોઈન્ટ્સ',
    points_subtext: 'પ્રેક્ટિસ દ્વારા મેળવેલ',
    reading_speed: 'વાંચન ઝડપ',
    speed_subtext: 'શબ્દો પ્રતિ મિનિટ',
    words_mastered: 'શીખેલા શબ્દો',
    vocab_subtext: 'શબ્દભંડોળમાં સંગ્રહિત',
    daily_study_plan: 'તમારી દૈનિક અભ્યાસ યોજના',
    daily_plan_desc: 'તમારી ક્ષમતા આધારિત ૩૦ મિનિટની AI અનુકૂલિત પ્રેક્ટિસ.',
    time_target: 'દૈનિક લક્ષ્ય',
    regenerate_plan: 'યોજના બદલો',
    start_activity: 'શરૂ કરો',
    completed: 'પૂર્ણ થયું',
    continue_learning: 'શીખવાનું ચાલુ રાખો',
    all_subjects: 'તમામ વિષયો',
    chapters_count: 'પ્રકરણો',
    questions_count: 'પ્રશ્નો',
    mastery_level: 'નિપુણતા સ્તર',
    start_subject: 'વિષય ખોલો',
    quick_practice: 'ઝડપી પ્રેક્ટિસ પ્રશ્નો',
    due_revisions: 'પુનરાવર્તન માટે બાકી વિષયો',
    revise_now: 'હમણાં પુનરાવર્તન કરો',
    recent_badges: 'તમારી સિદ્ધિઓ અને બેજ',

    chapter_roadmap: 'પ્રકરણ રોડમેપ અને પ્રેક્ટિસ',
    learning_objectives: 'શીખવાના હેતુઓ',
    est_time: 'અંદાજિત સમય',
    minutes: 'મિનિટ',
    start_chapter: 'પ્રકરણ શરૂ કરો',
    concept_notes: 'સિદ્ધાંત નોટ્સ અને સમજૂતી',
    practice_tab: 'પ્રેક્ટિસ અને ક્વિઝ',
    summary_tab: 'ઝડપી સારાંશ અને સૂત્રો',
    key_takeaways: 'મુખ્ય મુદ્દાઓ અને સૂત્રો',
    topics_in_chapter: 'આ પ્રકરણના વિષયો',
    difficulty: 'મુશ્કેલી સ્તર',
    easy: 'સરળ',
    medium: 'મધ્યમ',
    hard: 'કઠિન',
    advanced: 'ઉચ્ચ સ્તર',

    question_label: 'પ્રશ્ન',
    of_label: 'માંથી',
    check_answer: 'જવાબ તપાસો',
    next_question: 'આગળનો પ્રશ્ન',
    previous_question: 'પાછળનો પ્રશ્ન',
    show_hint: 'સંકેત જોઈએ છે?',
    hide_hint: 'સંકેત છુપાવો',
    explanation_title: 'તબક્કાવાર સમજૂતી',
    correct_feedback: 'સાચો જવાબ! ખૂબ સરસ! 🌟',
    incorrect_feedback: 'સાચું નથી. ચાલો સાચો ખ્યાલ સમજીએ:',
    practice_completed_title: 'પ્રેક્ટિસ સત્ર પૂર્ણ થયું! 🎉',
    your_score: 'તમારો સ્કોર',
    points_earned: 'મેળવેલા પોઈન્ટ્સ',
    retake_quiz: 'ફરીથી પ્રેક્ટિસ કરો',
    next_chapter: 'આગળના વિષય પર જાઓ',
    ask_ai_explain: 'AI ટ્યુટર પાસેથી વિગતવાર સમજૂતી મેળવો',

    search_placeholder: 'વિષયો, પ્રકરણો, પ્રશ્નો શોધો...',
    all_grades: 'તમામ ધોરણો',
    grade: 'ધોરણ',
    board: 'બોર્ડ',
    stream: 'પ્રવાહ',
    back_to_dashboard: '← ડેશબોર્ડ પર પાછા જાઓ',
    back_to_subjects: '← વિષયો પર પાછા જાઓ',
  },
};

// Subject Name Translations Dictionary across Indian Languages
export const SUBJECT_TRANSLATIONS: Record<string, Record<string, string>> = {
  // English key -> Localized Subject Name
  'Mathematics': {
    bn: 'গণিত',
    hi: 'गणित',
    mr: 'गणित',
    te: 'గణితం',
    ta: 'கணிதம்',
    gu: 'ગણિત',
    kn: 'ಗಣಿತ',
    ml: 'ഗണിതം',
    or: 'ଗଣିତ',
    pa: 'ਗਣਿਤ',
    as: 'গণিত',
    ur: 'ریاضی',
    sa: 'गणितम्',
  },
  'Science': {
    bn: 'বিজ্ঞান',
    hi: 'विज्ञान',
    mr: 'विज्ञान',
    te: 'సైన్స్',
    ta: 'அறிவியல்',
    gu: 'વિજ્ઞાન',
    kn: 'ವಿಜ್ಞಾನ',
    ml: 'ശാസ്ത്രം',
    or: 'ବିଜ୍ଞାନ',
    pa: 'ਵਿਗਿਆਨ',
    as: 'বিজ্ঞান',
    ur: 'سائنس',
    sa: 'विज्ञानम्',
  },
  'English': {
    bn: 'ইংরেজি',
    hi: 'अंग्रेजी',
    mr: 'इंग्रजी',
    te: 'ఇంగ్లీష్',
    ta: 'ஆங்கிலம்',
    gu: 'અંગ્રેજી',
    kn: 'ಇಂಗ್ಲಿಷ್',
    ml: 'ഇംഗ്ലീഷ്',
    or: 'ଇଂରାଜୀ',
    pa: 'ਅੰਗਰੇਜ਼ੀ',
    as: 'ইংৰাজী',
    ur: 'انگریزی',
    sa: 'आङ्ग्लभाषा',
  },
  'Environmental Studies': {
    bn: 'পরিবেশ বিদ্যা (EVS)',
    hi: 'पर्यावरण अध्ययन (EVS)',
    mr: 'पर्यावरण अभ्यास (EVS)',
    te: 'పర్యావరణ అధ్యయనాలు (EVS)',
    ta: 'சுற்றுச்சூழல் கல்வி (EVS)',
    gu: 'પર્યાવરણ અભ્યાસ (EVS)',
    kn: 'ಪರಿಸರ ಅಧ್ಯಯನ (EVS)',
    ml: 'പരിസ്ഥിതി പഠനം (EVS)',
    or: 'ପରିବେଶ ଅଧ୍ୟୟନ (EVS)',
    pa: 'ਵਾਤਾਵਰਣ ਅਧਿਐਨ (EVS)',
    as: 'পৰিৱেশ অধ্যয়ন (EVS)',
    ur: 'ماحولیاتی مطالعہ (EVS)',
    sa: 'पर्यावरणम्',
  },
  'Social Science': {
    bn: 'সমাজবিজ্ঞান',
    hi: 'सामाजिक विज्ञान',
    mr: 'सामाजिक शास्त्र',
    te: 'సాంఘిక శాస్త్రం',
    ta: 'சமூக அறிவியல்',
    gu: 'સામાજિક વિજ્ઞાન',
    kn: 'ಸಮಾಜ ವಿಜ್ಞಾನ',
    ml: 'സാമൂഹ്യശാസ്ത്രം',
    or: 'ସାମାଜିକ ବିଜ୍ଞାନ',
    pa: 'ਸਮਾਜਿਕ ਵਿਗਿਆਨ',
    as: 'সমাজ বিজ্ঞান',
    ur: 'سماجی علوم',
    sa: 'सामाजिकविज्ञानम्',
  },
  'Physics': {
    bn: 'পদার্থবিজ্ঞান',
    hi: 'भौतिक विज्ञान',
    mr: 'भौतिकशास्त्र',
    te: 'భౌతిక శాస్త్రం',
    ta: 'இயற்பியல்',
    gu: 'ભૌતિક વિજ્ઞાન',
    kn: 'ಭೌತಶಾಸ್ತ್ರ',
    ml: 'ഭൗതികശാസ്ത്രം',
    or: 'ପଦାର୍ଥ ବିଜ୍ଞାନ',
    pa: 'ਭੌਤਿਕ ਵਿਗਿਆਨ',
    as: 'পদাৰ্থ বিজ্ঞান',
    ur: 'طبیعیات',
    sa: 'भौतिकशास्त्रम्',
  },
  'Chemistry': {
    bn: 'রসায়ন বিজ্ঞান',
    hi: 'रसायन विज्ञान',
    mr: 'रसायनशास्त्र',
    te: 'రసాయన శాస్త్రం',
    ta: 'வேதியியல்',
    gu: 'રસાયણ વિજ્ઞાન',
    kn: 'ರಸಾಯನಶಾಸ್ತ್ರ',
    ml: 'രസതന്ത്രം',
    or: 'ରସାୟନ ବିଜ୍ଞାନ',
    pa: 'ਰਸਾਇਣ ਵਿਗਿਆਨ',
    as: 'ৰসায়ন বিজ্ঞান',
    ur: 'کیمیا',
    sa: 'रसायनशास्त्रम्',
  },
  'Biology': {
    bn: 'জীববিজ্ঞান',
    hi: 'जीव विज्ञान',
    mr: 'जीवशास्त्र',
    te: 'జీవశాస్త్రం',
    ta: 'உயிரியல்',
    gu: 'જીવવિજ્ઞાન',
    kn: 'ಜೀವಶಾಸ್ತ್ರ',
    ml: 'ജീവശാസ്ത്രം',
    or: 'ଜୀବ ବିଜ୍ଞାନ',
    pa: 'ਜੀਵ ਵਿਗਿਆਨ',
    as: 'জীৱবিজ্ঞান',
    ur: 'حیاتیات',
    sa: 'जीवशास्त्रम्',
  },
  'Computer Science': {
    bn: 'কম্পিউটার বিজ্ঞান ও কোডিং',
    hi: 'कंप्यूटर विज्ञान एवं कोडिंग',
    mr: 'संगणक शास्त्र आणि कोडिंग',
    te: 'కంప్యూటర్ సైన్స్ & కోడింగ్',
    ta: 'கணினி அறிவியல் & கோடிங்',
    gu: 'કમ્પ્યુટર વિજ્ઞાન અને કોડિંગ',
    kn: 'ಕಂಪ್ಯೂಟರ್ ಸೈನ್ಸ್ & ಕೋಡಿಂಗ್',
    ml: 'കംപ്യൂട്ടർ സയൻസ് & കോഡിംഗ്',
    or: 'କମ୍ପ୍ୟୁଟର ବିଜ୍ଞାନ',
    pa: 'ਕੰਪਿਊਟਰ ਵਿਗਿਆਨ',
    as: 'কম্পিউটাৰ বিজ্ঞান',
    ur: 'کمپیوٹر سائنس',
    sa: 'सङ्गणकविज्ञानम्',
  },
  'Hindi': {
    bn: 'হিন্দি ভাষা ও সাহিত্য',
    hi: 'हिन्दी भाषा एवं साहित्य',
    mr: 'हिंदी भाषा आणि साहित्य',
    te: 'హిందీ భాష & సాహిత్యం',
    ta: 'இந்தி மொழி & இலக்கியம்',
    gu: 'હિન્દી ભાષા અને સાહિત્ય',
    kn: 'ಹಿಂದಿ ಭಾಷೆ & ಸಾಹಿತ್ಯ',
    ml: 'ഹിന്ദി സാഹിത്യം',
    or: 'ହିନ୍ଦୀ ଭାଷା',
    pa: 'ਹਿੰਦੀ ਭਾਸ਼ਾ',
    as: 'হিন্দী ভাষা',
    ur: 'ہندی زبان',
    sa: 'हिन्दीभाषा',
  },
  'History': {
    bn: 'ইতিহাস',
    hi: 'इतिहास',
    mr: 'इतिहास',
    te: 'చరిత్ర',
    ta: 'வரலாறு',
    gu: 'ઇતિહાસ',
    kn: 'ಇತಿಹಾಸ',
    ml: 'ചരിത്രം',
    or: 'ଇତିହାସ',
    pa: 'ਇਤਿਹਾਸ',
    as: 'ইতিহাস',
    ur: 'تاریخ',
    sa: 'इतिहासः',
  },
  'Geography': {
    bn: 'ভূগোল',
    hi: 'भूगोल',
    mr: 'भूगोल',
    te: 'భూగోళశాస్త్రం',
    ta: 'புவியியல்',
    gu: 'ભૂગોળ',
    kn: 'ಭೂಗೋಳಶಾಸ್ತ್ರ',
    ml: 'ഭൂമിശാസ്ത്രം',
    or: 'ଭୂଗୋଳ',
    pa: 'ਭੂਗੋਲ',
    as: 'ভূগোল',
    ur: 'جغرافیہ',
    sa: 'भूगोलः',
  },
  'Economics': {
    bn: 'অর্থনীতি',
    hi: 'अर्थशास्त्र',
    mr: 'अर्थशास्त्र',
    te: 'అర్థశాస్త్రం',
    ta: 'பொருளாதாரம்',
    gu: 'અર્થશાસ્ત્ર',
    kn: 'ಅರ್ಥಶಾಸ್ತ್ರ',
    ml: 'സാമ്പത്തികശാസ്ത്രം',
    or: 'ଅର୍ଥଶାସ୍ତ୍ର',
    pa: 'ਅਰਥ ਸ਼ਾਸਤਰ',
    as: 'অৰ্থনীতি',
    ur: 'معاشیات',
    sa: 'अर्थशास्त्रम्',
  },
  'Accountancy': {
    bn: 'হিসাববিজ্ঞান',
    hi: 'लेखाशास्त्र (अकाउंटेंसी)',
    mr: 'लेखाकर्म',
    te: 'అకౌంటెన్సీ',
    ta: 'கணக்கியல்',
    gu: 'નામાના મૂળતત્વો',
    kn: 'ಲೆಕ್ಕಶಾಸ್ತ್ರ',
    ml: 'അക്കൗണ്ടൻസി',
    or: 'ହିସାବ ଶାସ୍ତ୍ର',
    pa: 'ਲੇਖਾਕਾਰੀ',
    as: 'হিচাপ বিজ্ঞান',
    ur: 'اکاؤنٹنسی',
    sa: 'लेखाशास्त्रम्',
  },
  'Business Studies': {
    bn: 'ব্যবসায় শিক্ষা',
    hi: 'व्यावसायिक अध्ययन',
    mr: 'वाणिज्य संघटन',
    te: 'బిజినెస్ స్టడీస్',
    ta: 'வணிகவியல்',
    gu: 'વાણિજ્ય વ્યવસ્થા',
    kn: 'ವ್ಯವಹಾರ ಅಧ್ಯಯನ',
    ml: 'ബിസിനസ് സ്റ്റഡീസ്',
    or: 'ବ୍ୟବସାୟ ଶିକ୍ଷା',
    pa: 'ਵਪਾਰ ਅਧਿਐਨ',
    as: 'ব্যৱসায় অধ্যয়ন',
    ur: 'بزنس اسٹڈیز',
    sa: 'वाणिज्यशास्त्रम्',
  },
};

// Chapter & Topic Translations Dictionary
export const CHAPTER_TOPIC_TRANSLATIONS: Record<string, Record<string, string>> = {
  // Math Chapters
  'Shapes and Space': {
    bn: 'আকার ও স্থান (Shapes & Space)',
    hi: 'आकृतियां और स्थान (Shapes & Space)',
    mr: 'आकार आणि जागा',
    te: 'ఆకారాలు మరియు స్థలం',
    ta: 'வடிவங்களும் இடமும்',
    gu: 'આકારો અને જગ્યા',
    kn: 'ಆಕಾರಗಳು ಮತ್ತು ಸ್ಥಳ',
    ml: 'രൂപങ്ങളും സ്ഥലവും',
  },
  'Numbers from One to Nine': {
    bn: 'এক থেকে নয় পর্যন্ত সংখ্যা',
    hi: 'एक से नौ तक की संख्याएं',
    mr: 'एक ते नऊ पर्यंतच्या संख्या',
    te: 'ఒకటి నుండి తొమ్మిది వరకు సంఖ్యలు',
    ta: 'ஒன்று முதல் ஒன்பது வரை எண்கள்',
    gu: 'એક થી નવ સુધીની સંખ્યાઓ',
  },
  'Addition': {
    bn: 'যোগ (Addition)',
    hi: 'जोड़ (Addition)',
    mr: 'बेरीज',
    te: 'కూడిక',
    ta: 'கூட்டல்',
    gu: 'સરવાળો',
  },
  'Subtraction': {
    bn: 'বিয়োগ (Subtraction)',
    hi: 'घटाव (Subtraction)',
    mr: 'वजाबाकी',
    te: 'తీసివేత',
    ta: 'கழித்தல்',
    gu: 'બાદબાકી',
  },
  'Multiplication': {
    bn: 'গুণ (Multiplication)',
    hi: 'गुणा (Multiplication)',
    mr: 'गुणाकार',
    te: 'గుణకారం',
    ta: 'பெருக்கல்',
    gu: 'ગુણાકાર',
  },
  'Division': {
    bn: 'ভাগ (Division)',
    hi: 'भाग (Division)',
    mr: 'भागाकार',
    te: 'భాగహారం',
    ta: 'வகுத்தல்',
    gu: 'ભાગાકાર',
  },
  'Time Goes On': {
    bn: 'সময় ও ক্যালেন্ডার (Time & Calendar)',
    hi: 'समय और कैलेंडर (Time & Calendar)',
    mr: 'काळ आणि दिनदर्शिका',
    te: 'సమయం మరియు క్యాలెండర్',
    ta: 'நேரமும் காலண்டரும்',
    gu: 'સમય અને કેલેન્ડર',
  },
  'Fractions and Decimals': {
    bn: 'ভগ্নাংশ ও দশমিক (Fractions & Decimals)',
    hi: 'भिन्न और दशमलव (Fractions & Decimals)',
    mr: 'अपूर्णांक आणि दशांश',
    te: 'భిన్నాలు మరియు దశాంశాలు',
    ta: 'பின்னங்களும் தசமங்களும்',
    gu: 'અપૂર્ણાંક અને દશાંશ',
  },
  'Number Systems & Real Numbers': {
    bn: 'সংখ্যা পদ্ধতি ও বাস্তব সংখ্যা',
    hi: 'संख्या पद्धति एवं वास्तविक संख्याएं',
    mr: 'संख्या पद्धती आणि वास्तव संख्या',
    te: 'సంఖ్యా వ్యవస్థ మరియు వాస్తవ సంఖ్యలు',
    ta: 'எண் அமைப்புகளும் மெய் எண்களும்',
    gu: 'સંખ્યા પદ્ધતિ અને વાસ્તવિક સંખ્યાઓ',
  },
  'Polynomials & Algebra': {
    bn: 'বহুপদী ও বীজগণিত (Polynomials & Algebra)',
    hi: 'बहुपद एवं बीजगणित (Polynomials & Algebra)',
    mr: 'बहुपदी आणि बीजगणित',
    te: 'బహుపదులు మరియు బీజగణితం',
    ta: 'பல்லுறுப்புக் கோவைகளும் இயற்கணிதமும்',
    gu: 'બહુપદીઓ અને બીજગણિત',
  },
  'Coordinate Geometry': {
    bn: 'স্থানাঙ্ক জ্যামিতি (Coordinate Geometry)',
    hi: 'निर्देशांक ज्यामिति (Coordinate Geometry)',
    mr: 'निर्देशांक भूमिती',
    te: 'నిరూపక రేఖాగణితం',
    ta: 'ஆயத்தொலைவு வடிவியல்',
    gu: 'યામ ભૂમિતિ',
  },
  'Linear Equations in Two Variables': {
    bn: 'দুই চলক বিশিষ্ট রৈখিক সমীকরণ',
    hi: 'दो चरों वाले रैखिक समीकरण',
    mr: 'दोन चलांमधील रेषीय समीकरणे',
    te: 'రెండు చరరాశులలో సరళ సమీకరణాలు',
    ta: 'இரு மாறிகளில் நேரியல் சமன்பாடுகள்',
    gu: 'દ્વિચલ સુરેખ સમીકરણો',
  },
  'Triangles & Trigonometry': {
    bn: 'ত্রিভুজ ও ত্রিকোণমিতি (Trigonometry)',
    hi: 'त्रिभुज एवं त्रिकोणमिति (Trigonometry)',
    mr: 'त्रिकोण आणि त्रिकोणमिती',
    te: 'త్రిభుజాలు మరియు త్రికోణమితి',
    ta: 'முக்கோணங்களும் முக்கோணவியலும்',
    gu: 'ત્રિકોણ અને ત્રિકોણમિતિ',
  },
  'Circles & Constructions': {
    bn: 'বৃত্ত ও জ্যামিতিক অঙ্কন (Circles)',
    hi: 'वृत्त एवं रचनाएं (Circles)',
    mr: 'वर्तुळ आणि रचना',
    te: 'వృత్తాలు మరియు నిర్మాణాలు',
    ta: 'வட்டங்களும் அமைப்புகளும்',
    gu: 'વર્તુળ અને રચનાઓ',
  },
  'Surface Areas and Volumes': {
    bn: 'পৃষ্ঠতলের ক্ষেত্রফল ও আয়তন (Mensuration)',
    hi: 'पृष्ठीય क्षेत्रफल एवं आयतन (Mensuration)',
    mr: 'पृष्ठफळ आणि घनफळ',
    te: 'ఉపరితల వైశాల్యాలు మరియు ఘనపరిమాణాలు',
    ta: 'புறப்பரப்பளவும் கனஅளவும்',
    gu: 'પૃષ્ઠફળ અને ઘનફળ',
  },
  'Statistics and Probability': {
    bn: 'পরিসংখ্যান ও সম্ভাবনা (Statistics & Probability)',
    hi: 'सांख्यिकी एवं प्रायिकता (Probability)',
    mr: 'संख्याशास्त्र आणि संभाव्यता',
    te: 'సాంఖ్యకశాస్త్రం మరియు సంభావ్యత',
    ta: 'புள்ளியியலும் நிகழ்தகவும்',
    gu: 'આંકડાશાસ્ત્ર અને સંભાવના',
  },

  // Science Chapters
  'Matter in Our Surroundings': {
    bn: 'আমাদের চারপাশের পদার্থ (Matter Around Us)',
    hi: 'हमारे आस-पास के पदार्थ (Matter Around Us)',
    mr: 'आपल्या सभोवतालचे द्रव्य',
    te: 'మన పరిసరాలలోని పదార్థం',
    ta: 'நம்மைச் சுற்றியுள்ள பருப்பொருட்கள்',
    gu: 'આપણી આસપાસમાં દ્રવ્ય',
  },
  'Is Matter Around Us Pure': {
    bn: 'আমাদের চারপাশের পদার্থ কি বিশুদ্ধ?',
    hi: 'क्या हमारे आस-पास के पदार्थ शुद्ध हैं?',
    mr: 'आपल्या सभोवतालचे द्रव्य शुद्ध आहे का?',
    te: 'మన చుట్టూ ఉన్న పదార్థం స్వచ్ఛమైనదేనా?',
    ta: 'நம்மைச் சுற்றியுள்ள பருப்பொருள் தூய்மையானதா?',
    gu: 'આપણી આસપાસના દ્રવ્યો શુદ્ધ છે?',
  },
  'Atoms and Molecules': {
    bn: 'পরমাণু ও অণু (Atoms & Molecules)',
    hi: 'परमाणु एवं अणु (Atoms & Molecules)',
    mr: 'अणू आणि रेणू',
    te: 'పరమాణువులు మరియు అణువులు',
    ta: 'அணுக்களும் மூலக்கூறுகளும்',
    gu: 'પરમાણુઓ અને અણુઓ',
  },
  'Structure of the Atom': {
    bn: 'পরমাণুর গঠন (Structure of Atom)',
    hi: 'परमाणु की संरचना (Structure of Atom)',
    mr: 'अणूची रचना',
    te: 'పరమాణు నిర్మాణం',
    ta: 'அணுவின் அமைப்பு',
    gu: 'પરમાણુનું બંધારણ',
  },
  'The Fundamental Unit of Life: Cell': {
    bn: 'জীবনের মৌলিক একক: কোষ (Cell Biology)',
    hi: 'जीवन की मौलिक इकाई: कोशिका (Cell)',
    mr: 'जीवनाची मूलभूत एकक: पेशी',
    te: 'జీవ ప్రాథమిక ప్రమాణం: కణం',
    ta: 'உயிரின் அடிப்படை அலகு: செல்',
    gu: 'સજીવનો પાયાનો એકમ: કોષ',
  },
  'Tissues in Plants & Animals': {
    bn: 'উদ্ভিদ ও প্রাণীর কলা (Tissues)',
    hi: 'पादप एवं जंतु ऊतक (Tissues)',
    mr: 'उती',
    te: 'కణజాలాలు',
    ta: 'திசுக்கள்',
    gu: 'પેશીઓ',
  },
  'Motion & Kinematics': {
    bn: 'গতি ও গতিবিদ্যা (Motion)',
    hi: 'गति एवं गतिकी (Motion)',
    mr: 'गती आणि तिचे नियम',
    te: 'చలనం మరియు చలన నియమాలు',
    ta: 'இயக்கம்',
    gu: 'ગતિ',
  },
  'Force and Laws of Motion': {
    bn: 'বল ও গতির সূত্রাবলী (Force & Newton Laws)',
    hi: 'बल एवं गति के नियम (Force & Laws of Motion)',
    mr: 'बल आणि गतीचे नियम',
    te: 'బలం మరియు చలన నియమాలు',
    ta: 'விசையும் இயக்க விதிகளும்',
    gu: 'બળ અને ગતિના નિયમો',
  },
  'Gravitation & Free Fall': {
    bn: 'মহাকর্ষ ও মুক্ত পতন (Gravitation)',
    hi: 'गुरुत्वाकर्षण एवं मुक्त पतन (Gravitation)',
    mr: 'गुरुत्वाकर्षण',
    te: 'గురుత్వాకర్షణ',
    ta: 'ஈர்ப்பியல்',
    gu: 'ગુરુત્વાકર્ષણ',
  },
  'Work, Energy & Power': {
    bn: 'কার্য, শক্তি ও ক্ষমতা (Work & Energy)',
    hi: 'कार्य, ऊर्जा एवं शक्ति (Work & Energy)',
    mr: 'कार्य आणि ऊर्जा',
    te: 'పని మరియు శక్తి',
    ta: 'வேலை மற்றும் ஆற்றல்',
    gu: 'કાર્ય અને ઊર્જા',
  },
  'Sound Waves & Acoustics': {
    bn: 'শব্দ তরঙ্গ ও ধ্বনিবিজ্ঞান (Sound)',
    hi: 'ध्वनि तरंगें एवं ध्वनिकी (Sound)',
    mr: 'ध्वनी',
    te: 'ధ్వని',
    ta: 'ஒலி',
    gu: 'ધ્વનિ',
  },
  'Light: Reflection & Refraction': {
    bn: 'আলো: প্রতিফলন ও প্রতিসরণ (Light)',
    hi: 'प्रकाश: परावर्तन एवं अपवर्तन (Light)',
    mr: 'प्रकाश: परावर्तन आणि अपवर्तन',
    te: 'కాంతి: పరావర్తనం మరియు వక్రీభవనం',
    ta: 'ஒளி: எதிரொளிப்பு மற்றும் ஒளிவிலகல்',
    gu: 'પ્રકાશ: પરાવર્તન અને વક્રીભવન',
  },
  'Electricity & Electric Circuits': {
    bn: 'তড়িৎ ও বৈদ্যুতিক বর্তনী (Electricity)',
    hi: 'विद्युत एवं विद्युत परिपथ (Electricity)',
    mr: 'विद्युतधारा आणि परिपथ',
    te: 'విద్యుత్ మరియు విద్యుత్ వలయాలు',
    ta: 'மின்னோட்டமும் மின்சுற்றுகளும்',
    gu: 'વિદ્યુત અને વિદ્યુત પરિપથ',
  },
};

// Common Question Phrase Localizers (translates question starters, options, explanations)
const QUESTION_PATTERNS: Array<{
  matchRegex: RegExp;
  translations: Record<string, string>;
}> = [
  {
    matchRegex: /A little puppy is sleeping inside its cozy doghouse\. Where is the puppy\?/i,
    translations: {
      bn: 'একটি ছোট্ট কুকুরছানা তার আরামদায়ক ঘরে ঘুমাচ্ছে। কুকুরছানাটি কোথায় রয়েছে?',
      hi: 'एक छोटा पिल्ला अपने आरामदायक घर के अंदर सो रहा है। पिल्ला कहाँ है?',
      mr: 'एक लहान पिल्लू आपल्या घरात झोपले आहे. पिल्लू कोठे आहे?',
      te: 'ఒక చిన్న కుక్కపిల్ల తన ఇంట్లో నిద్రపోతోంది. కుక్కపిల్ల ఎక్కడ ఉంది?',
      ta: 'ஒரு சிறிய நாய்க்குட்டி அதன் கூண்டுக்குள் தூங்குகிறது. நாய்க்குட்டி எங்கே உள்ளது?',
      gu: 'એક નાનું કુરકુરિયું તેના ઘરમાં સૂઈ રહ્યું છે. કુરકુરિયું ક્યાં છે?',
    },
  },
  {
    matchRegex: /Which of the following objects can ROLL easily across the floor\?/i,
    translations: {
      bn: 'নিচের কোন বস্তুটি মেঝের উপর সহজেই গড়িয়ে (ROLL) যেতে পারে?',
      hi: 'निम्नलिखित में से कौन सी वस्तु फर्श पर आसानी से लुढ़क (ROLL) सकती है?',
      mr: 'खालीलपैकी कोणती वस्तू जमिनीवर सहज लोळू (ROLL) शकते?',
      te: 'క్రింది వాటిలో ఏ వస్తువు నేలపై సులభంగా దొర్లుతుంది (ROLL)?',
      ta: 'பின்வரும் பொருட்களில் எது தரையில் எளிதாக உருளக்கூடியது (ROLL)?',
      gu: 'નીચેનામાંથી કઈ વસ્તુ જમીન પર સરળતાથી ગબડી (ROLL) શકે છે?',
    },
  },
  {
    matchRegex: /Count the stars:.*How many stars are there in total\?/i,
    translations: {
      bn: 'তারাগুলো গণনা করুন: ★ ★ ★ ★ ★। মোট কতটি তারা রয়েছে?',
      hi: 'तारे गिनिए: ★ ★ ★ ★ ★। कुल कितने तारे हैं?',
      mr: 'तारे मोजा: ★ ★ ★ ★ ★। एकूण किती तारे आहेत?',
      te: 'నక్షత్రాలను లెక్కించండి: ★ ★ ★ ★ ★. మొత్తం ఎన్ని నక్షత్రాలు ఉన్నాయి?',
      ta: 'நட்சத்திரங்களை எண்ணுங்கள்: ★ ★ ★ ★ ★. மொத்தம் எத்தனை நட்சத்திரங்கள் உள்ளன?',
      gu: 'તારાઓ ગણો: ★ ★ ★ ★ ★. કુલ કેટલા તારાઓ છે?',
    },
  },
  {
    matchRegex: /What is the result of/i,
    translations: {
      bn: 'নিচের হিসাবটির ফলাফল কী:',
      hi: 'का परिणाम क्या है:',
      mr: 'चे उत्तर काय आहे:',
      te: 'యొక్క ఫలితం ఏమిటి:',
      ta: 'இதன் முடிவு என்ன:',
      gu: 'નું પરિણામ શું છે:',
    },
  },
  {
    matchRegex: /Which of the following is correct\?/i,
    translations: {
      bn: 'নিচের কোনটি সঠিক?',
      hi: 'निम्नलिखित में से कौन सा सही है?',
      mr: 'खालीलपैकी कोणते बरोबर आहे?',
      te: 'క్రింది వాటిలో ఏది సరైనది?',
      ta: 'பின்வருவனவற்றில் எது சரியானது?',
      gu: 'નીચેનામાંથી કયું સાચું છે?',
    },
  },
  {
    matchRegex: /Identify the correct formula for/i,
    translations: {
      bn: 'সঠিক সূত্রটি চিহ্নিত করুন:',
      hi: 'के लिए सही सूत्र पहचानें:',
      mr: 'यासाठी योग्य सूत्र ओळखा:',
      te: 'సరైన సూత్రాన్ని గుర్తించండి:',
      ta: 'சரியான சூத்திரத்தை அடையாளம் காணவும்:',
      gu: 'માટે સાચું સૂત્ર ઓળખો:',
    },
  },
  {
    matchRegex: /Calculate the value of/i,
    translations: {
      bn: 'মান নির্ণয় করুন:',
      hi: 'का मान ज्ञात कीजिए:',
      mr: 'ची किंमत काढा:',
      te: 'విలువను లెక్కించండి:',
      ta: 'மதிப்பைக் கணக்கிடுங்கள்:',
      gu: 'નું મૂલ્ય ગણો:',
    },
  },
  {
    matchRegex: /What is the SI unit of/i,
    translations: {
      bn: 'এর SI একক কী:',
      hi: 'का SI मात्रक क्या है:',
      mr: 'चे SI एकक काय आहे:',
      te: 'యొక్క SI ప్రమాణం ఏమిటి:',
      ta: 'இதன் SI அலகு என்ன:',
      gu: 'નો SI એકમ શું છે:',
    },
  },
];

// Common Option Localizers
const OPTION_TRANSLATIONS: Record<string, Record<string, string>> = {
  'Inside the doghouse': {
    bn: 'ঘরের ভিতরে (Inside)',
    hi: 'घर के अंदर (Inside)',
    mr: 'घराच्या आत',
    te: 'ఇంటి లోపల',
    ta: 'வீட்டின் உள்ளே',
    gu: 'ઘરની અંદર',
  },
  'Outside the doghouse': {
    bn: 'ঘরের বাইরে (Outside)',
    hi: 'घर के बाहर (Outside)',
    mr: 'घराच्या बाहेर',
    te: 'ఇంటి వెలుపల',
    ta: 'வீட்டின் வெளியே',
    gu: 'ઘરની બહાર',
  },
  'On the roof': {
    bn: 'ছাদের উপর',
    hi: 'छत के ऊपर',
    mr: 'छतावर',
    te: 'పైకప్పుపై',
    ta: 'கூரை மீது',
    gu: 'છત પર',
  },
  'Under the tree': {
    bn: 'গাছের নিচে',
    hi: 'पेड़ के नीचे',
    mr: 'झाडाखाली',
    te: 'చెట్టు కింద',
    ta: 'மரத்தின் கீழ்',
    gu: 'ઝાડ નીચે',
  },
  'A round football': {
    bn: 'একটি গোলাকার ফুটবল (A round football)',
    hi: 'एक गोल फुटबॉल (A round football)',
    mr: 'एक गोल फुटबॉल',
    te: 'గుండ్రని ఫుట్‌బాల్',
    ta: 'ஒரு உருண்டையான கால்பந்து',
    gu: 'ગોળાકાર ફૂટબોલ',
  },
  'A square brick': {
    bn: 'একটি চারকোনা ইট',
    hi: 'एक चौकोर ईंट',
    mr: 'एक चौकोनी वीट',
    te: 'చతురస్రాకార ఇటుక',
    ta: 'ஒரு செவ்வக செங்கல்',
    gu: 'ચોરસ ઈંટ',
  },
  'A wooden dice': {
    bn: 'একটি কাঠের ছক্কা (লুডো ডাইস)',
    hi: 'एक लकड़ी का पासा',
    mr: 'लाकडी फासा',
    te: 'చెక్క పాచిక',
    ta: 'ஒரு மர பகடை',
    gu: 'લાકડાનો પાસો',
  },
  'A flat book': {
    bn: 'একটি সমতল বই',
    hi: 'एक चपटी किताब',
    mr: 'एक सपाट पुस्तक',
    te: 'ఫ్లాట్ పుస్తకం',
    ta: 'ஒரு தட்டையான புத்தகம்',
    gu: 'સપાટ પુસ્તક',
  },
  'True': {
    bn: 'সত্য (True)',
    hi: 'सत्य (True)',
    mr: 'सत्य (True)',
    te: 'నిజం (True)',
    ta: 'சரி (True)',
    gu: 'સાચું (True)',
  },
  'False': {
    bn: 'মিথ্যা (False)',
    hi: 'असत्य (False)',
    mr: 'असत्य (False)',
    te: 'తప్పు (False)',
    ta: 'தவறு (False)',
    gu: 'ખોટું (False)',
  },
};

/**
 * Universal Localization Function: t(key, defaultText, lang)
 */
export function getTranslation(key: string, lang: string = 'en', defaultText?: string): string {
  if (COMPREHENSIVE_UI_TRANSLATIONS[lang]?.[key]) {
    return COMPREHENSIVE_UI_TRANSLATIONS[lang][key];
  }
  if (COMPREHENSIVE_UI_TRANSLATIONS['en']?.[key]) {
    return COMPREHENSIVE_UI_TRANSLATIONS['en'][key];
  }
  return defaultText || key;
}

/**
 * Localize a Subject title and description
 */
export function localizeSubject(subject: Subject, lang: string = 'en'): Subject {
  if (lang === 'en' || !subject) return subject;

  // Check direct subject name dictionary
  const localizedName = SUBJECT_TRANSLATIONS[subject.name]?.[lang] || subject.name;
  
  // Localize category / description if available
  let localizedDesc = subject.description;
  if (subject.name === 'Mathematics' && lang === 'bn') {
    localizedDesc = 'মৌলিক পাটিগণিত, বীজগণিত, জ্যামিতি এবং ব্যবহারিক গণিত।';
  } else if (subject.name === 'Science' && lang === 'bn') {
    localizedDesc = 'পরিবেশ বিজ্ঞান, সাধারণ বিজ্ঞান, পদার্থবিজ্ঞান এবং জীববিজ্ঞান।';
  } else if (subject.name === 'English' && lang === 'bn') {
    localizedDesc = 'ভাষা শিক্ষা, শব্দভাণ্ডার, ব্যাকরণ এবং পাঠ অনুধাবন।';
  } else if (subject.name === 'Mathematics' && lang === 'hi') {
    localizedDesc = 'बुनियादी अंकगणित, बीजगणित, ज्यामिति और व्यावहारिक गणित।';
  } else if (subject.name === 'Science' && lang === 'hi') {
    localizedDesc = 'पर्यावरण विज्ञान, सामान्य विज्ञान, भौतिकी और जीवविज्ञान।';
  }

  return {
    ...subject,
    name: localizedName,
    description: localizedDesc,
  };
}

/**
 * Localize a Chapter title and description
 */
export function localizeChapter(chapter: Chapter, lang: string = 'en'): Chapter {
  return localizeChapterFn(chapter, lang);
}

/**
 * Localize a Topic title and summary
 */
export function localizeTopic(topic: Topic, lang: string = 'en'): Topic {
  return localizeTopicFn(topic, lang);
}

/**
 * Localize a Lesson: title, sections (title, content, analogy, example), and key takeaways
 */
export function localizeLesson(lesson: Lesson | undefined, lang: string = 'en'): Lesson | undefined {
  if (!lesson || lang === 'en') return lesson;

  const locSections = lesson.sections.map((sec) => {
    let title = sec.title;
    let content = sec.content;
    let analogy = sec.analogy;
    let example = sec.example;

    if (lang === 'hi') {
      title = title.replace(/^(\d+\.\s*)What is (.*?)\?/, '$1$2 क्या है?');
      title = title.replace(/^(\d+\.\s*)Real-World Applications of (.*)/, '$1$2 के वास्तविक जीवन में उपयोग');
      title = title.replace(/^(\d+\.\s*)How to Master (.*)/, '$1$2 में कैसे महारत हासिल करें');
      
      content = content.replace(/Welcome! In this lesson from (.*?) \((.*?)\), we will learn about (.*?) in simple words\./g, 
        'स्वागत है! $1 ($2) के इस पाठ में, हम सरल शब्दों में $3 के बारे में सीखेंगे।');
      content = content.replace(/You will understand what it means, why it matters, and how to remember it easily without any confusion\./g,
        'आप समझेंगे कि इसका क्या अर्थ है, यह क्यों महत्वपूर्ण है, और इसे बिना किसी भ्रम के आसानी से कैसे याद रखें।');
      content = content.replace(/Key Principles to Remember:/g, 'याद रखने योग्य मुख्य सिद्धांत:');
      content = content.replace(/1\. Break down complex problems into smaller, manageable steps\./g, '1. जटिल समस्याओं को छोटे, प्रबंधनीय चरणों में विभाजित करें।');
      content = content.replace(/2\. Look for core patterns and connect them to foundational concepts\./g, '2. मुख्य पैटर्न पहचानें और उन्हें बुनियादी अवधारणाओं से जोड़ें।');
      content = content.replace(/3\. Verify your reasoning through logical checks and practice problems\./g, '3. तार्किक जांच और अभ्यास प्रश्नों के माध्यम से अपने तर्क की पुष्टि करें।');

      if (analogy) {
        analogy = analogy.replace(/Think of (.*?) like (.*?)\./g, '$1 को $2 की तरह समझें।');
      }
    } else if (lang === 'bn') {
      title = title.replace(/^(\d+\.\s*)What is (.*?)\?/, '$1$2 কী?');
      title = title.replace(/^(\d+\.\s*)Real-World Applications of (.*)/, '$1$2-এর বাস্তব প্রয়োগ');
      content = content.replace(/Welcome! In this lesson from (.*?) \((.*?)\), we will learn about (.*?) in simple words\./g, 
        'স্বাগতম! $1 ($2)-এর এই পাঠে আমরা সহজ কথায় $3 সম্পর্কে জানব।');
    }

    return {
      ...sec,
      title,
      content,
      analogy,
      example,
    };
  });

  let locTakeaways = lesson.keyTakeaways;
  if (lang === 'hi' && locTakeaways) {
    locTakeaways = locTakeaways.map((item) => {
      let t = item;
      t = t.replace(/Understand the foundational definitions and why they are essential\./g, 'बुनियादी परिभाषाओं और उनके महत्व को अच्छी तरह समझें।');
      t = t.replace(/Practice step-by-step applications to build speed and accuracy\./g, 'गति और सटीकता बढ़ाने के लिए चरण-दर-चरण अभ्यास करें।');
      t = t.replace(/Review common mistakes and self-correct during problem solving\./g, 'समस्या समाधान के दौरान सामान्य गलतियों की समीक्षा करें और आत्म-सुधार करें।');
      return t;
    });
  }

  let locTitle = lesson.title;
  if (lang === 'hi') {
    locTitle = locTitle.replace(/(.*?) - Easy Learning Guide/g, '$1 - आसान अध्ययन मार्गदर्शिका');
  } else if (lang === 'bn') {
    locTitle = locTitle.replace(/(.*?) - Easy Learning Guide/g, '$1 - সহজ শিক্ষার নির্দেশিকা');
  }

  return {
    ...lesson,
    title: locTitle,
    sections: locSections,
    keyTakeaways: locTakeaways,
  };
}

/**
 * Localize a Question: prompt, options, explanation, hints
 * Using full multi-lingual curriculum question translation engine
 */
export function localizeQuestion(question: Question, lang: string = 'en'): Question {
  return localizeQuestionFn(question, lang);
}

export { localizeQuestionFn, localizeChapterFn, localizeTopicFn };

